version: '3'
services:
  golang:
    image: amaysim/golang:1.8.3
    env_file: .env
    volumes:
      - ${GOPATH}/src:/go/src

  go-shim:
    image: eawsy/aws-lambda-go-shim
    env_file: .env
    volumes:
      - ${GOPATH}/src:/go/src

  serverless:
    image: amaysim/serverless:1.14.0
    env_file: .env
    volumes:
      - .:/build
      - ~/.aws:/root/.aws:ro
    working_dir: /build
