service: github-trending-feed

custom:
  bucket: kekfeed

package:
  artifact: ${env:PACKAGE}.zip

provider:
  name: aws
  runtime: python2.7
  stage: ${env:ENV}
  memorySize: 128
  timeout: 300
  region: eu-west-1
  #profile: #uncomment and set profile name if using non-default aws profile

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource: "arn:aws:s3:::${self:custom.bucket}"
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "s3:PutObjectAcl"
        - "s3:GetObject"
        - "s3:GetObjectAcl"
        - "s3:DeleteObject"
      Resource: "arn:aws:s3:::${self:custom.bucket}/*"

functions:
  github-trending-feed:
    handler: ${env:HANDLER}.Handle
    environment:
      S3_BUCKET: ${self:custom.bucket}
    events:
      - schedule:
          rate: rate(2 hours)

resources:
  Resources:
    MemeBucket:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        BucketName: ${self:custom.bucket}
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: error.html
